// Mock data used when Supabase is not configured
export const mockFoodPosts = [
  {
    id: 1,
    name: 'Margherita Pizza',
    description: 'Crispy crust, gooey mozzarella, fresh basil, and perfect sauce. 10/10',
    location: 'Joe\'s Pizza, NYC',
    price: 5,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&h=800&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: 2,
    name: 'Tonkotsu Ramen',
    description: 'Rich pork broth, perfectly chewy noodles, soft-boiled egg. Soul warming.',
    location: 'Ichiran Ramen, Shibuya',
    price: 14,
    image_url: 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=600&h=800&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: 3,
    name: 'Fish Tacos',
    description: 'Battered cod, lime crema, pickled onion, fresh cilantro. Beachy vibes.',
    location: 'Baja Fish Tacos, LA',
    price: 8,
    image_url: 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=600&h=800&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Croissant',
    description: 'Buttery, flaky, golden perfection. Paired with a cappuccino.',
    location: 'Du Pain et des Idées, Paris',
    price: 4,
    image_url: 'https://images.unsplash.com/photo-1555507036-ab1f4038024a?w=600&h=800&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Pad Thai',
    description: 'Sweet, sour, salty, spicy — all in one bite. Street food perfection.',
    location: 'Thipsamai, Bangkok',
    price: 3,
    image_url: 'https://images.unsplash.com/photo-1559314809-0d155014e29e?w=600&h=800&fit=crop',
    created_at: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Smash Burger',
    description: 'Crispy edges, juicy center, melted American cheese. Simple and perfect.',
    location: 'Shake Shack, NYC',
    price: 9,
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&h=800&fit=crop',
    created_at: new Date().toISOString(),
  },
]
